import { Inter } from "next/font/google";
import "./globals.css";
import Top from "./(components)/Top";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#000000] `}>
        <div className="h-screen bg-[#000000] mx-6">
          <div className="mt-8 ">{children}</div>
        </div>
      </body>
    </html>
  );
}
